<a href="https://colab.research.google.com/github/Kaio1394/Curso-ciencia-de-dados/blob/master/Melbourne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import regex as re

In [49]:
data = pd.read_csv('MELBOURNE_HOUSE_PRICES_LESS.csv')

In [ ]:
# Colunas do dataframe
data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Postcode', 'Regionname', 'Propertycount', 'Distance',
       'CouncilArea'],
      dtype='object')

In [ ]:
# Exibição das 5 primeiras linhas
data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council

In [ ]:
# Quantidade de linhas
len(data)

63023

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63023 entries, 0 to 63022
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         63023 non-null  object
 1   Address        63023 non-null  object
 2   Rooms          63023 non-null  int64
 3   Type           63023 non-null  object
 4   Price          48433 non-null  float64
 5   Method         63023 non-null  object
 6   SellerG        63023 non-null  object
 7   Date           63023 non-null  object
 8   Postcode       63023 non-null  int64
 9   Regionname     63023 non-null  object
 10  Propertycount  63023 non-null  int64
 11  Distance       63023 non-null  float64
 12  CouncilArea    63023 non-null  object
dtypes: float64(2), int64(3), object(8)
memory usage: 6.3+ MB

In [43]:
data.isna().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price            14590
Method               0
SellerG              0
Date                 0
Postcode             0
Regionname           0
Propertycount        0
Distance             0
CouncilArea          0
dtype: int64

In [50]:
# Trocando valores NaN por zero
data['Price'] = data['Price'].fillna(0)

# Preços com valores zerados
data.loc[data['Price'] == 0.0]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
8,Albanvale,1 Jackson Cct,6,h,0.0,PI,hockingstuart,1/04/2017,3021,Western Metropolitan,1899,14.0,Brimbank City Council
15,Altona Meadows,57 Tatman Dr,4,h,0.0,SN,Barry,1/04/2017,3028,Western Metropolitan,7630,15.5,Hobsons Bay City Council
24,Ashburton,1 Pitt St,4,h,0.0,S,Jellis,1/04/2017,3147,Southern Metropolitan,3052,10.2,Boroondara City Council
29,Attwood,46 Threadneedle St,4,h,0.0,SN,Barry,1/04/2017,3049,Northern Metropolitan,1130,16.5,Hume City Council
38,Balwyn North,12 Agnes Av,3,h,0.0,SP,Fletchers,1/04/2017,3104,Southern Metropolitan,7809,9.7,Boroondara City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63001,Wyndham Vale,15 Yaltara Dr,3,h,0.0,S,hockingstuart,30/12/2017,3024,Western Metropolitan,5262,27.2,Wyndham City Council
63008,Yarraville,4/247 Williamstown Rd,3,t,0.0,S,Jas,30/12/2017,3013,Western Metropolitan,6543,6.3,Maribyrnong City Council
63010,Burwood,29 Summit Rd,4,h,0.0,PN,@Realty,31/03/2018,3125,Southern Metropolitan,5678,10.4,Monash City Council
63021,Thomastown,3/1 Travers St,3,u,0.0,PI,Barry,31/03/2018,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
63022,Williams Landing,1 Diadem Wy,4,h,0.0,SP,Aussie,31/03/2018,3027,Western Metropolitan,1999,17.6,Wyndham City Council

In [13]:
# Casa com valor de preço maior
data.sort_values('Price', ascending=False)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
23841,Canterbury,49 Mangarra Rd,5,h,8000000.0,VB,Sotheby's,13/05/2017,3126.0,Southern Metropolitan,3265.0,8.4,Boroondara City Council
1593,Toorak,12 Hill St,5,h,6700000.0,VB,Marshall,1/09/2018,3142.0,Southern Metropolitan,7217.0,4.1,Stonnington City Council
7825,Armadale,507 Orrong Rd,10,h,6600000.0,S,Marshall,5/05/2018,3143.0,Southern Metropolitan,4836.0,6.3,Stonnington City Council
17683,Malvern,6 Moorakyne Av,5,h,6600000.0,S,Jellis,9/12/2017,3144.0,Southern Metropolitan,4675.0,5.9,Stonnington City Council
24587,Kew,15 Barry St,6,h,6500000.0,S,Jellis,13/08/2016,3101.0,Southern Metropolitan,10331.0,5.4,Boroondara City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27196,St Kilda,3/11 Herbert St,2,u,NaN,S,Biggin,14/10/2017,3182.0,Southern Metropolitan,13240.0,5.0,Port Phillip City Council
27214,Surrey Hills,61A Broughton Rd,4,t,NaN,VB,Fletchers,14/10/2017,3127.0,Southern Metropolitan,5457.0,10.2,Boroondara City Council
27225,Templestowe,2/2 Wyena Wy,2,u,NaN,S,Jellis,14/10/2017,3106.0,Eastern Metropolitan,6202.0,15.5,Manningham City Council
27232,Thornbury,72 Ballantyne St,3,h,NaN,S,Kaio,14/10/2017,3071.0,Northern Metropolitan,8870.0,7.0,Darebin City Council
27241,Toorak,699 Malvern Rd,4,h,NaN,S,Marshall,14/10/2017,3142.0,Southern Metropolitan,7217.0,4.1,Stonnington City Council

In [ ]:
# Filtrando dados
filter = data.loc[(data['Rooms'] == 3) & (data['Type'] == 'h') & data['Price'] <= 200000]
filter

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3.0,h,1490000.0,S,Jellis,1/04/2017,3067.0,Northern Metropolitan,4019.0,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3.0,h,1220000.0,S,Marshall,1/04/2017,3067.0,Northern Metropolitan,4019.0,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3.0,h,1420000.0,S,Nelson,1/04/2017,3067.0,Northern Metropolitan,4019.0,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3.0,h,1515000.0,S,Barry,1/04/2017,3040.0,Western Metropolitan,1543.0,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2.0,h,670000.0,S,Nelson,1/04/2017,3042.0,Western Metropolitan,3464.0,10.4,Moonee Valley City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54366,Epping,53 Hayston Bvd,3.0,h,465000.0,S,Harcourts,27/05/2017,3076.0,Northern Metropolitan,10926.0,19.6,Whittlesea City Council
54367,Epping,13 Orlit Ct,4.0,h,545000.0,PI,Barry,27/05/2017,3076.0,Northern Metropolitan,10926.0,19.6,Whittlesea City Council
54368,Epping,14A Supply Dr,2.0,h,452500.0,S,Barry,27/05/2017,3076.0,Northern Metropolitan,10926.0,19.6,Whittlesea City Council
54369,Essendon,9 Amelia Av,4.0,h,1577000.0,S,Hodges,27/05/2017,3040.0,Western Metropolitan,9264.0,7.5,Moonee Valley City Council
54370,Essendon,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Usando regex para filtrar os dados**

In [ ]:
# Filtrando com o método contains()
# 'turner st|turner Rd' -> contains('Turner St' or 'Turner Rd')
# 'flags'=re.I -> ignora letras maísculas
filter = data.loc[data['Address'].str.contains('turner st|turner Rd', flags=re.I)]
filter

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
1,Abbotsford,59A Turner St,3.0,h,1220000.0,S,Marshall,1/04/2017,3067.0,Northern Metropolitan,4019.0,3.0,Yarra City Council
2859,Malvern East,24 Turner St,6.0,h,4700000.0,S,RT,3/03/2018,3145.0,Southern Metropolitan,8801.0,8.4,Stonnington City Council
4723,Highett,48 Turner Rd,2.0,h,832000.0,S,Buxton,3/09/2017,3190.0,Southern Metropolitan,4794.0,16.0,Bayside City Council
4987,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,3/12/2016,3067.0,Northern Metropolitan,4019.0,3.0,Yarra City Council
7501,Highett,28 Turner Rd,3.0,h,NaN,PI,Nick,4/08/2018,3190.0,Southern Metropolitan,4794.0,16.0,Bayside City Council
9647,Abbotsford,53 Turner St,2.0,h,NaN,S,Biggin,6/08/2016,3067.0,Northern Metropolitan,4019.0,3.0,Yarra City Council
9648,Abbotsford,99 Turner St,2.0,h,NaN,S,Collins,6/08/2016,3067.0,Northern Metropolitan,4019.0,3.0,Yarra City Council
14012,Berwick,4 Turner St,5.0,h,536000.0,S,O'Brien,8/04/2017,3806.0,Eastern Victoria,17093.0,35.2,Casey City Council
14745,Westmeadows,16 Turner St,3.0,h,NaN,SN,Stockdale,8/04/2017,3049.0,Northern Metropolitan,2474.0,16.5,Hume City Council
18960,Moonee Ponds,3/16 Turner St,2.0,u,550000.0,VB,Woodards,10/09/2016,3039.0,Western Metropolitan,6232.0,6.2,Moonee Valley City Council
19148,Abbotsford,106/119 Turner St,1.0,u,481000.0,SP,Purplebricks,10/12/2016,3067.0,Northern Metropolitan,4019.0,3.0,Yarra City Council
19609,Highett,2/20 Turner Rd,2.0,u,730000.0,SP,Buxton,10/12/2016,3190.0,Southern Metropolitan,4794.0,16.0,Bayside City Council
20043,Westmeadows,14 Turner St,3.0,h,586000.0,S,Stockdale,10/12/2016,3049.0,Northern Metropolitan,2474.0,16.5,Hume City Council
20717,Langwarrin,49 Turner Rd,4.0,h,NaN,PI,UFirst,11/08/2018,3910.0,Eastern Victoria,8743.0,41.0,Frankston City Council
25081,Moonee Ponds,15/3 Turner St,3.0,t,732000.0,S,Nelson,13/10/2018,3039.0,Western Metropolitan,6232.0,6.2,Moonee Valley City Council
26305,Abbotsford,2 Turner St,3.0,h,1620000.0,S,Biggin,14/07/2018,3067.0,Northern Metropolitan,4019.0,3.0,Yarra City Council
29650,Briar Hill,10 Turner St,2.0,h,812000.0,S,Darren,16/06/2018,3088.0,Eastern Metropolitan,1390.0,16.1,Banyule City Council
36217,Westmeadows,25 Turner St,4.0,h,685000.0,S,Jason,18/06/2016,3049.0,Northern Metropolitan,2474.0,16.5,Hume City Council
39873,Highett,3/6 Turner Rd,3.0,u,NaN,PI,Buxton,20/05/2017,3190.0,Southern Metropolitan,4794.0,16.0,Bayside City Council
41985,Highett,1/6 Turner Rd,4.0,h,921000.0,S,Buxton,22/04/2017,3190.0,Southern Metropolitan,4794.0,16.0,Bayside City Council
42537,Malvern East,16 Turner St,4.0,h,NaN,S,Marshall,22/05/2016,3145.0,Southern Metropolitan,8801.0,8.4,Stonnington City Council
45597,Highett,3/15 Turner Rd,2.0,u,770000.0,S,McGrath,23/09/2017,3190.0,Southern Metropolitan,4794.0,16.0,Bayside City Council
47333,Malvern East,27 Turner St,2.0,h,1040000.0,S,Jellis,24/02/2018,3145.0,Southern Metropolitan,8801.0,8.4,Stonnington City Council
47843,Berwick,6 Turner St,4.0,h,1400000.0,VB,Peake,24/03/2018,3806.0,Eastern Victoria,17093.0,35.2,Casey City Council
49480,Abbotsford,31 Turner St,4.0,h,1542000.0,S,Collins,24/09/2016,3067.0,Northern Metropolitan,4019.0,3.0,Yarra City Council
49890,Moonee Ponds,4/6 Turner St,2.0,u,600000.0,S,Woodards,24/09/2016,3039.0,Western Metropolitan,6232.0,6.2,Moonee Valley City Council
50254,Briar Hill,7 Turner St,4.0,h,1100000.0,S,Jellis,25/02/2017,3088.0,Eastern Metropolitan,1390.0,16.1,Banyule City Council
51364,Malvern East,29 Turner St,2.0,h,1010000.0,SP,Jellis,25/08/2018,3145.0,Southern Metropolitan,8801.0,8.4,Stonnington City Council
53753,Highett,2/4 Turner Rd,2.0,u,680500.0,S,Ray,26/08/2017,3190.0,Southern Metropolitan,4794.0,16.0,Bayside City Council

In [8]:
# '^59' -> Inicie como 59
filter = data.loc[data['Address'].str.contains('^59') & (data['Price'] <= 1000000)]
filter

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
182,Croydon,59 Wicklow Av,3,h,965000.0,S,Carter,1/04/2017,3136.0,Eastern Metropolitan,11925.0,23.0,Maroondah City Council
770,Craigieburn,59 Balyang Wy,4,h,607000.0,S,@Realty,1/07/2017,3064.0,Northern Metropolitan,15510.0,20.6,Hume City Council
797,Eltham,59 Bible St,3,h,975000.0,S,Morrison,1/07/2017,3095.0,Eastern Metropolitan,6990.0,18.0,Banyule City Council
807,Epping,59 Greenfields Dr,4,h,940000.0,SP,Iconek,1/07/2017,3076.0,Northern Metropolitan,10926.0,19.6,Whittlesea City Council
1698,Braybrook,59 South Rd,3,h,700000.0,VB,Barry,2/06/2018,3019.0,Western Metropolitan,3589.0,8.6,Maribyrnong City Council
2220,Wallan,59 William St,3,h,424000.0,S,Ruralco,2/06/2018,3756.0,Northern Victoria,3988.0,44.2,Mitchell Shire Council
2341,North Melbourne,59 Baillie St,2,t,880000.0,S,Rendina,3/02/2018,3051.0,Northern Metropolitan,6821.0,1.8,Melbourne City Council
4210,Montmorency,59 Lilicur Rd,4,h,870000.0,S,Fletchers,3/09/2016,3094.0,Eastern Metropolitan,3891.0,16.2,Banyule City Council
5309,Frankston South,59 Towerhill Rd,3,h,610000.0,S,Harcourts,3/12/2016,3199.0,South-Eastern Metropolitan,7566.0,38.0,Frankston City Council
6465,Narre Warren,59 Saxonwood Dr,4,h,680000.0,SP,O'Brien,4/03/2017,3805.0,South-Eastern Metropolitan,9376.0,34.1,Casey City Council
7038,Heidelberg Heights,59 Southern Rd,3,h,580000.0,VB,Miles,4/06/2016,3081.0,Eastern Metropolitan,2947.0,8.8,Banyule City Council
8383,Werribee,59 Church St,3,h,630000.0,S,YPA,5/05/2018,3030.0,Western Metropolitan,16166.0,14.7,Wyndham City Council
8989,Point Cook,59 Breasley Pky,3,h,670000.0,S,hockingstuart,6/01/2018,3030.0,Western Metropolitan,15542.0,14.7,Wyndham City Council
9096,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,6/01/2018,3429.0,Western Metropolitan,14092.0,31.7,Hume City Council
10075,Abbotsford,59/84 Trenerry Cr,2,u,750000.0,VB,Biggin,6/10/2018,3067.0,Northern Metropolitan,4019.0,3.0,Yarra City Council
10577,Williamstown,59 Princes St,3,h,850000.0,VB,Greg,6/10/2018,3016.0,Western Metropolitan,6380.0,6.8,Hobsons Bay City Council
10635,Boronia,59 Gertonia Av,3,h,715000.0,SA,Purplebricks,7/04/2018,3155.0,Eastern Metropolitan,9704.0,25.0,Knox City Council
12421,Oakleigh South,596 Warrigal Rd,4,h,813500.0,S,Buxton,7/10/2017,3167.0,South-Eastern Metropolitan,3692.0,15.5,Kingston City Council
12855,Heidelberg West,59 Alamein Rd,3,h,532000.0,S,Miles,7/11/2016,3081.0,Eastern Metropolitan,2674.0,8.8,Banyule City Council
13089,Sunshine West,59 Felstead Av,3,h,465000.0,S,Bells,7/11/2016,3020.0,Western Metropolitan,6763.0,10.5,Brimbank City Council
13733,Point Cook,59 Breasley Pky,3,h,670000.0,S,hockingstuart,8/01/2018,3030.0,Western Metropolitan,15542.0,14.7,Wyndham City Council
13840,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,8/01/2018,3429.0,Western Metropolitan,14092.0,31.7,Hume City Council
14744,Westmeadows,59 Raleigh St,2,h,607000.0,S,Stockdale,8/04/2017,3049.0,Northern Metropolitan,2474.0,16.5,Hume City Council
15697,Sunshine,59 Parsons St,4,h,850000.0,PI,Barry,8/09/2018,3020.0,Western Metropolitan,3755.0,10.5,Brimbank City Council
16113,Kensington,59 The Crescent,3,t,918000.0,SP,Kaio,8/10/2016,3031.0,Northern Metropolitan,5263.0,3.4,Melbourne City Council
17353,Coburg,59a Barrow St,2,t,680000.0,PI,Ray,9/12/2017,3058.0,Northern Metropolitan,11204.0,6.7,Darebin City Council
18799,Flemington,59 Victoria St,2,h,730000.0,SP,Kaio,10/09/2016,3031.0,Northern Metropolitan,3593.0,3.4,Melbourne City Council
19616,Hoppers Crossing,59 Aitken Av,3,h,421600.0,SP,Barry,10/12/2016,3029.0,Western Metropolitan,13830.0,18.4,Wyndham City Council
19623,Hoppers Crossing,59 Mossfiel Dr,3,h,453000.0,S,Triwest,10/12/2016,3029.0,Western Metropolitan,13830.0,18.4,Wyndham City Council
20332,Wantirna,59 Dunbarton Dr,4,h,855000.0,S,Harcourts,11/02/2017,3152.0,Eastern Metropolitan,5424.0,14.7,Knox City Council
23594,Spotswood,59 Hope St,4,h,850000.0,VB,RT,12/11/2016,3015.0,Western Metropolitan,1223.0,6.2,Hobsons Bay City Council
24161,Niddrie,59 Hoffmans Rd,3,h,944000.0,S,Barry,13/05/2017,3042.0,Western Metropolitan,2291.0,10.4,Moonee Valley City Council
25168,Ringwood East,59 Sunbeam Av,3,h,785000.0,S,Barry,13/10/2018,3135.0,Eastern Metropolitan,4407.0,21.3,Maroondah City Council
25186,South Melbourne,59/39 Dorcas St,2,u,606000.0,S,Greg,13/10/2018,3205.0,Southern Metropolitan,5943.0,1.9,Port Phillip City Council
25236,Tullamarine,59 Spring St,3,h,620000.0,SP,RW,13/10/2018,3043.0,Western Metropolitan,3296.0,12.9,Brimbank City Council
25387,Craigieburn,59 Langdon Cr,3,h,617000.0,S,Stockdale,14/04/2018,3064.0,Northern Metropolitan,15510.0,20.6,Hume City Council
26379,Craigieburn,59 Champion Pde,4,h,797000.0,S,Ray,14/07/2018,3064.0,Northern Metropolitan,15510.0,20.6,Hume City Council

In [51]:
# Trocando valores da tabela
data.loc[data['SellerG'] == 'Nelson', 'SellerG'] = 'Kaio'

In [52]:
# Confirmando valore trocado
data.loc[data['SellerG'] == 'Kaio']

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Kaio,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Kaio,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
7,Airport West,1/26 Highridge Cr,3,h,715000.0,SP,Kaio,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
50,Bellfield,1/15 Toohey St,3,u,675000.0,SP,Kaio,1/04/2017,3081,Eastern Metropolitan,790,8.8,Banyule City Council
94,Brunswick,53 Amelia St,2,h,740000.0,PI,Kaio,1/04/2017,3056,Northern Metropolitan,11918,5.2,Moreland City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
62841,Reservoir,2/61 Marchant Av,2,t,600000.0,S,Kaio,30/12/2017,3073,Northern Metropolitan,21650,12.0,Darebin City Council
62843,Reservoir,19 Ramleh Rd,4,h,890000.0,S,Kaio,30/12/2017,3073,Northern Metropolitan,21650,12.0,Darebin City Council
62847,Richmond,37 Cutter St,3,h,1490000.0,S,Kaio,30/12/2017,3121,Northern Metropolitan,14949,2.4,Yarra City Council
62851,Richmond,81 Wellington St,2,h,1145000.0,S,Kaio,30/12/2017,3121,Northern Metropolitan,14949,2.4,Yarra City Council
62901,Strathmore,3/40 Glenbervie Rd,3,u,900000.0,VB,Kaio,30/12/2017,3041,Western Metropolitan,3284,8.2,Moonee Valley City Council

In [53]:
data.loc[data['SellerG'] == 'Kaio', 'Method'] = 'P'
data.loc[data['SellerG'] == 'Kaio']

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
2,Abbotsford,119B Yarra St,3,h,1420000.0,P,Kaio,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,P,Kaio,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
7,Airport West,1/26 Highridge Cr,3,h,715000.0,P,Kaio,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
50,Bellfield,1/15 Toohey St,3,u,675000.0,P,Kaio,1/04/2017,3081,Eastern Metropolitan,790,8.8,Banyule City Council
94,Brunswick,53 Amelia St,2,h,740000.0,P,Kaio,1/04/2017,3056,Northern Metropolitan,11918,5.2,Moreland City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
62841,Reservoir,2/61 Marchant Av,2,t,600000.0,P,Kaio,30/12/2017,3073,Northern Metropolitan,21650,12.0,Darebin City Council
62843,Reservoir,19 Ramleh Rd,4,h,890000.0,P,Kaio,30/12/2017,3073,Northern Metropolitan,21650,12.0,Darebin City Council
62847,Richmond,37 Cutter St,3,h,1490000.0,P,Kaio,30/12/2017,3121,Northern Metropolitan,14949,2.4,Yarra City Council
62851,Richmond,81 Wellington St,2,h,1145000.0,P,Kaio,30/12/2017,3121,Northern Metropolitan,14949,2.4,Yarra City Council
62901,Strathmore,3/40 Glenbervie Rd,3,u,900000.0,P,Kaio,30/12/2017,3041,Western Metropolitan,3284,8.2,Moonee Valley City Council